# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='attrList',
            field=models.CharField(default=False, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='settingsFile',
            field=models.CharField(default=False, max_length=1000),
            preserve_default=False,
        ),
    ]
