# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160910_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='settingsFile',
            new_name='output_file',
        ),
    ]
